### ISSUE TITLE
Hidding Input in Text Fields

### ISSUE THREAD

**Issue by tataDan** [richardwilkes/unison#11]
Is there a way to cause a text field to display asterisks instead of the actual input (e.g. when entering a password)? I looked for a function such as `fld.SetEditable(false)`, but did not find one.

**Comment by richardwilkes** [comment]
No, since I’ve not needed that functionality. That’s a reasonable request, though, and shouldn’t be difficult to implement.

**Comment by richardwilkes** [comment]
This turns out to be considerably more work than I had originally thought it would take, since it essentially requires tracking two strings independently - one for display, containing nothing but • characters, and another for the actual content. Still shouldn't be terribly difficult, but it means I'm punting on it right now while I work on some other tasks I have.

**Comment by tataDan** [comment]
While waiting for a suitable solution, I have been experimenting with a temporary workaround (that some might consider to be a inelegant kludge).  I downloaded a font called "password" that contains only dots for every character.  In my application directory I created a directory named "resources" and under that directory I created another directory named "fonts". I then copied `password.ttf` to the `fonts` directory.

In my application I have the following code:
```
//go:embed resources/fonts
var fontFS embed.FS

func NewMainWindow(title string, where unison.Point) (*unison.Window, error) {
...
passwordFld := createTextField("Password:", panel)

	var PasswordFont = &unison.IndirectFont{}
	const fontDir = "resources/fonts"
	entries, err := fontFS.ReadDir(fontDir)
	if err != nil {
		jot.Error(errs.NewWithCause("unable to read embedded file system", err))
		// return
	}
	for _, entry := range entries {
		if entry.Type().IsRegular() {
			name := entry.Name()
			lower := strings.ToLower(name)
			if strings.HasSuffix(lower, ".otf") || strings.HasSuffix(lower, ".ttf") {
				var data []byte
				if data, err = fontFS.ReadFile(path.Join(fontDir, name)); err != nil {
					jot.Error(errs.NewWithCausef(err, "unable to read font %s", name))
				} else if _, err = unison.RegisterFont(data); err != nil {
					jot.Error(errs.NewWithCause(name, err))
				}
			}
		}
	}
	passwordFamilyName := "password"
	baseSize := float32(10)
	PasswordFont.Font = unison.MatchFontFace(passwordFamilyName, unison.MediumFontWeight, unison.StandardSpacing, unison.NoSlant).Font(baseSize)
	passwordFld.FieldTheme.Font = PasswordFont
...
}
```
Testing shows that it appears to do what I want it to do.  However, there might some problems with it that are not currently obvious to me and there could very well be a better solution.

**Comment by richardwilkes** [comment]
That's an interesting way to solve the issue without burdening the code with tracking a shadow string.

Do you have a link to the font in question? Does its license permit me to use and include it in unison? If so, I might just go that route.

**Comment by tataDan** [comment]
I found a font that looks better at [password stars font](https://fontstruct.com/fontstructions/show/1393506/b1-password-2).
Because `fontstruct.com` requires you to create an account to download files, I am attaching  the zip file that I downloaded: 
[b1-password-stars.zip](https://github.com/richardwilkes/unison/files/9578176/b1-password-stars.zip). It contains information about the license.
I had to change the font family name like so: `passwordFamilyName := "B1 Password Stars"`.

**Comment by richardwilkes** [comment]
Turns out that doesn't quite work 100%. Specifically, some characters I can type show up. On a Mac, for example, shift-option-k produces the Apple symbol. In addition, any emoji characters I input show up, such as smiley faces.

**Comment by richardwilkes** [comment]
Turns out the implementation didn't need to track any shadow text after all, so I was able to do without any special font. This also permits you to use whatever replacement character you want.

**Comment by tataDan** [comment]
With this new feature I only need to add `passwordFld.ObscurementRune = '●'` to my code to get the desired results. I am convinced that others will find this feature useful as well. Thanks for your time and effort in this matter.
