### ISSUE TITLE
Skia Linux arm64 not found

### ISSUE THREAD

**Issue by ddkwork** [richardwilkes/unison#14]
system is manjaro linux arm64 latest.
Instead on Android mobile use termux.

![Screenshot_20220925_152121_com.realvnc.viewer.android.jpg](https://user-images.githubusercontent.com/19886504/192132812-5c337481-e639-44de-a352-d5dff0a747a1.jpg)

**Comment by ddkwork** [comment]
![Screenshot_20220925_152507_com.termux.jpg](https://user-images.githubusercontent.com/19886504/192132868-515f3d82-b8a0-46b0-a639-3af8b75a9564.jpg)

**Comment by richardwilkes** [comment]
I've only built things for darwin-amd64, darwin-arm64, linux-amd64, and windows-amd64. I don't currently have plans for any other permutations. I suspect it isn't much effort to make work, but since I lack the necessary hardware, I won't be attempting it myself.
