### ISSUE TITLE
Need refresh when moving from one display to another

### ISSUE THREAD

**Issue by raff** [richardwilkes/unison#15]
On MacOS when moving from one display to another the window is blank. I need to resize it to get the content back.
It should probably automatically refresh, unless it's also resized.

**Comment by richardwilkes** [comment]
Hmm... it works as expected on all of my macOS machines (i.e. it doesn't need to be resized to see the content). I wonder if graphics RAM is low for you for some reason?

**Comment by raff** [comment]
I wouldn't think so. This is on a MacBook Pro 2019 running MacOS 13 beta going from builtin display (16" 3072x1920) to an Apple Thunderbolt 27" (2560x1440). It could be the beta, or the old monitor. I may be able to test with a different monitor in a few days (as soon as I get it installed).

Everything else works great! Let me know if there is anything else I can try.

**Comment by richardwilkes** [comment]
Yeah, that does seem like it would more than adequate, unless you had some graphics-intense app running at the same time that was consuming most of the VRAM.

If I could reproduce it, I'd be happy to look into ways to fix it... but I'm not currently able to do so. I have a fairly wide array of machines and haven't seen this particular problem. I've explicitly looked for it on a iMac Pro (2017), a Mac mini (2012), a MacBookPro 16" (2019), a MacBookPro 16" (2021, Apple M1 Max), and a MacBookPro 16" (2021, Intel). I have a few other machines I could try, but those cover a fairly broad spectrum.

Can you think of any particular steps you took that I may have overlooked?

**Comment by richardwilkes** [comment]
Hmm... I wonder if it has to do with moving from a retina display to a non-retina display, or vice-versa. All of my machines have either all retina-equivalent displays or non-retina displays, so I haven't tried that permutation. I'll see if I can find some time to set one up that way and give it a whirl.

**Comment by richardwilkes** [comment]
Also could be if the display scaling is different between the monitors (which is essentially what happens on the retina vs. non-retina).

**Comment by raff** [comment]
Again, I have a new monitor that I need to install. It should have a higher resolution that the old Apple Thunderbolt. I'll let you know if the issue goes away.

I tried to change the scaling of my displays but for the retina it doesn't really tell me the pixel resolution but just a "Large text" to "More space" scale, while for the Thunderbolt it gives me the pixel resolution, so it's hard to match. In any case the problem persists also when trying to change the settings.

**Comment by richardwilkes** [comment]
IIRC, if you hold down the option key when selecting the "Scaled" radio button, it will show you a list of resolutions rather than the pretty icons.

**Comment by raff** [comment]
So, I got the new monitor installed, with a higher resolution (but still not the same as the retina display) and I still have the problem. With Ventura it doesn't seem I can get the list of resolutions for the MacBook monitor (it only shows the icons).

**Comment by richardwilkes** [comment]
Really? That's unfortunate. I use the option key all the time so that I can pick exact resolutions.

**Comment by richardwilkes** [comment]
Have you tried adding some code to force a redraw if you detect the window is on another monitor to see if that fixes the issue for you?

**Comment by richardwilkes** [comment]
I guess I should be more explicit. On the `Window` object, you can set a `MovedCallback` and a `ResizedCallback`. Install those callbacks and inside them, check to see if the window's current placement overlaps a different monitor than previously. You can get the positions of all displays from `unison.AllDisplays()`

**Comment by richardwilkes** [comment]
If that turns out to be a viable solution for your case, I could add some code to unison to do that automatically without the need to install any callbacks. I just don't want to do it if it isn't going to actually help -- and I can't test it for myself at the moment.

**Comment by raff** [comment]
I'll give it a try tomorrow and let you know. I agree you shouldn't add code you can't really test, and I am happy to help.

**Comment by richardwilkes** [comment]
Any luck?

**Comment by raff** [comment]
Sorry, I got sidetracked :)

So, I tried again today on a different monitor and I get a slightly different result. I also tried adding a MovedCallback with a call to window.MarkForRedraw with no success. I am attaching my sample app (just something I was toying with).
[sample.go.txt](https://github.com/richardwilkes/unison/files/9687995/sample.go.txt)

So with this other monitor I get the following:

Start on retina display:
<img width="141" alt="original_on_retina" src="https://user-images.githubusercontent.com/53832/193365229-5bb58be0-5025-4e17-a877-35e148cef473.png">

Move to 2nd monitor:
![moveto_2nd_monitor](https://user-images.githubusercontent.com/53832/193365264-3302d6ac-da42-4e1b-86ed-255f57b83dcc.png)

Resize:
![resize_on_2nd_monitor](https://user-images.githubusercontent.com/53832/193365280-68b18c66-f009-4e46-892d-48ab3204f2be.png)

Move back to retina display:
<img width="150" alt="back_to_retina" src="https://user-images.githubusercontent.com/53832/193365307-bf201e23-b6f7-48d2-9e95-c98692aa8aad.png">

**Comment by raff** [comment]
I guess I am missing one, if I resize when back on retina display, the text goes back to the original dimensions.

**Comment by raff** [comment]
So, it does seems it's not registering the change of dpi between the monitors and/or failing to properly redraw on the change.

**Comment by richardwilkes** [comment]
Yep, failing to notice the resolution change is the most likely culprit.

**Comment by richardwilkes** [comment]
If you try commenting out the conditional on window.go:680 (and the corresponding brace on window.go:692), does that help? I'm wondering if there is something similar to what goes on with Linux and a small delay before coordinate changes register properly.

**Comment by raff** [comment]
No changes.

**Comment by raff** [comment]
Some more experiments: if you look at the value returned by window.GetBackingScale here:
https://github.com/richardwilkes/unison/blob/main/window.go#L924, I get 2, 2 for the retina display and 1,1 for the external display. 

If I change sx, sy to always be 2, 2 I get something that it's almost correct (the font on the external display is a littly fuzzy but looks like the correct size). Then if I resize the window, the font gets bigger (but clear) so there is still something else going on on the "resize" that seem to "fix" what the move on the external display did.

**Comment by richardwilkes** [comment]
I suspect that skia's internal buffers aren't getting updated until a resize occurs. Until that happens, it is likely just scaling the existing content to fit, which results in blurriness. This has to do with the underlying surface I create... but knowing when it needs to change is the trick. Anyway, at some point, I'll dig out an old monitor and hook it up so I can see this in action.
