### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by ddkwork** [richardwilkes/unison#18]
use fyne
![image](https://user-images.githubusercontent.com/19886504/193462104-ffe0cbeb-2fa2-4e53-982b-93460dcb27cd.png)

use unison
![image](https://user-images.githubusercontent.com/19886504/193462496-a5c8ba66-3fd8-46a2-a6e4-56020ec33bab.png)

i am still can`t layout use unison, can you help me,thank you very much.
rep:
https://github.com/ddkwork/unisonUi

**Comment by richardwilkes** [comment]
No, I don't have the time nor energy required to provide instruction on how to use unison. I provide it free of charge, but am developing specifically for my own needs. At some point in the future -- definitely after I'm no longer changing it on regular basis -- I might  take the time to write up some documentation. Until then, you'll have to get by on the comments and reading the code.

**Comment by ddkwork** [comment]
> No, I don't have the time nor energy required to provide instruction on how to use unison. I provide it free of charge, but am developing specifically for my own needs. At some point in the future -- definitely after I'm no longer changing it on regular basis -- I might  take the time to write up some documentation. Until then, you'll have to get by on the comments and reading the code.

Ok. Thx
