### ISSUE TITLE
 Panel SetSizer and SetBorder 

### ISSUE THREAD

**Issue by ddkwork** [richardwilkes/unison#21]
sorry my bad english, please see gif.

![screenshots](https://user-images.githubusercontent.com/19886504/205483842-9c6ba4c1-b1f7-4db5-bf10-8cb50f084626.gif)

**Comment by ddkwork** [comment]
hi, teacher, why does the setting panel set the size and boder not take effect? When the single linked list format tree of the table is opened, the panel under the table will be moved to the bottom, and there is no area to display it.

**Comment by richardwilkes** [comment]
You need to place the table inside a ScrollPanel

**Comment by ddkwork** [comment]
> You need to place the table inside a ScrollPanel and set the size of the ScrollPanel instead

thank you very much，teacher.
