### ISSUE TITLE
sort table will panic and table.SetSizer will lost scrollArea with the sync

### ISSUE THREAD

**Issue by ddkwork** [richardwilkes/unison#36]
![screenshots](https://github.com/richardwilkes/unison/assets/19886504/dfe0780a-fcd4-48ab-9392-87e15722cda3)

```

package demo

import (
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/richardwilkes/unison"
)

const topLevelRowsToMake = 100

var tableCounter int

// NewDemoTableWindow creates and displays our demo table window.
func NewDemoTableWindow(where unison.Point) (*unison.Window, error) {
	// Create the window
	tableCounter++
	wnd, err := unison.NewWindow(fmt.Sprintf("Table #%d", tableCounter))
	if err != nil {
		return nil, err
	}

	content := wnd.Content()
	content.SetLayout(&unison.FlexLayout{Columns: 1})

	// Create the table
	table := unison.NewTable[*demoRow](&unison.SimpleTableModel[*demoRow]{})
	table.HierarchyColumnID = 1
	table.Columns = make([]unison.ColumnInfo, 4)
	for i := range table.Columns {
		table.Columns[i].ID = i
		table.Columns[i].Minimum = 80
		table.Columns[i].Maximum = 10000
	}
	_, checkColSize, _ := unison.NewCheckBox().Sizes(unison.Size{})
	table.Columns[0].Minimum = checkColSize.Width
	table.Columns[0].Maximum = checkColSize.Width

	table.SetSizer(func(_ unison.Size) (min, pref, max unison.Size) {
		pref.Width = 220
		pref.Height = 220
		return min, pref, unison.MaxSize(max)
	})

	go func() {
		root := &demoRow{
			table:     table,
			parent:    nil,
			id:        uuid.New(),
			text:      fmt.Sprint(0),
			text2:     "ok2",
			children:  nil,
			container: false,
			open:      false,
		}
		for i := 0; i < 1000; i++ {
			child := &demoRow{
				table:     table,
				parent:    nil,
				id:        uuid.New(),
				text:      fmt.Sprint(i),
				text2:     "ok2",
				children:  nil,
				container: false,
				open:      false,
			}
			//if i == 3 {
			//	child.children = make([]*demoRow, 2)
			//	child.children = append(child.children, child)
			//	child.SetOpen(true)
			//	child.container = true
			//}
			root.AddRow(child)
			table.SetRootRows(root.children)

			table.ValidateScrollRoot()
			table.RequestFocus()

			lastNodeIndex := len(root.children) - 1
			selMap := map[uuid.UUID]bool{
				root.children[lastNodeIndex].id: true,
			}
			table.SetSelectionMap(selMap)
			table.ScrollRowCellIntoView(table.LastSelectedRowIndex(), 0)
			table.ScrollRowCellIntoView(table.FirstSelectedRowIndex(), 0)

			//m.table.EventuallySyncToModel()
			//m.table.EventuallySyncToModel()
			//m.table.EventuallySizeColumnsToFit(true)
			time.Sleep(60 * time.Millisecond)
		}
	}()

	table.SizeColumnsToFit(true)
	table.InstallDragSupport(nil, "demoRow", "Row", "Rows")
	unison.InstallDropSupport[*demoRow, any](table, "demoRow",
		func(from, to *unison.Table[*demoRow]) bool { return from == to }, nil, nil)

	header := unison.NewTableHeader[*demoRow](table,
		unison.NewTableColumnHeader[*demoRow]("", ""),
		unison.NewTableColumnHeader[*demoRow]("First", ""),
		unison.NewTableColumnHeader[*demoRow]("Second", ""),
		unison.NewTableColumnHeader[*demoRow]("xyz", ""),
	)
	header.SetLayoutData(&unison.FlexLayoutData{
		HAlign: unison.FillAlignment,
		VAlign: unison.FillAlignment,
		HGrab:  true,
	})
	content.AddChild(header)

	// Create a scroll panel and place a table panel inside it
	scrollArea := unison.NewScrollPanel()
	scrollArea.SetContent(table, unison.FillBehavior, unison.FillBehavior)
	scrollArea.SetLayoutData(&unison.FlexLayoutData{
		HAlign: unison.FillAlignment,
		VAlign: unison.FillAlignment,
		HGrab:  true,
		VGrab:  true,
	})
	content.AddChild(scrollArea)

	// Pack our window to fit its content, then set its location on the display and make it visible.
	wnd.Pack()
	rect := wnd.FrameRect()
	rect.Point = where
	wnd.SetFrameRect(rect)
	wnd.ToFront()

	return wnd, nil
}

func (d *demoRow) AddRow(rowData *demoRow) {
	d.parent = d
	d.children = append(d.children, rowData)
}

```

**Comment by richardwilkes** [comment]
Please copy and paste the actual error here, too. Since I have several large programs that use this extensively, I suspect it is something you’re doing in your code, not the library. The stack trace should tell us exactly what went wrong.

**Comment by ddkwork** [comment]
> Please copy and paste the actual error here, too. Since I have several large programs that use this extensively, I suspect it is something you’re doing in your code, not the library. The stack trace should tell us exactly what went wrong.

If make all nodes and call setrootdata method will work well, but if we dynamic add a node and use root's children as setrootdata arg, it will call syncmodel, and then calculate the selected node'uuid, this map uuid :book fileid will panic in a go fun case.

**Comment by ddkwork** [comment]
> This code of yours:
> 
> ```
> func (d *demoRow) AddRow(rowData *demoRow) {
> 	d.parent = d
> 	d.children = append(d.children, rowData)
> }
> ```
> 
> Appears to be broken. That does not correctly add a node and instead creates an infinite loop. While I don't know specifically what you're trying to achieve, I suspect -- at a minimum -- the code should look more like this:
> 
> ```
> func (d *demoRow) AddRow(rowData *demoRow) {
> 	rowData.parent = d
> 	d.children = append(d.children, rowData)
> }
> ```

```
                                      [main.main] C:/Users/Admin/Desktop/table bug/example/main.go:10
                                    Caused by: runtime error: invalid memory address or nil pointer dereference
ERR | 2023-06-03 | 09:10:13.162 | recovered from panic
                                      [table_bug/example/demo.(*demoRow).UUID] C:/Users/Admin/Desktop/table bug/example/demo/demo_row.go:48
                                      [github.com/richardwilkes/unison.(*Table[...]).IsRowOrAnyParentSelected] C:/Users/Admin/go/pkg/mod/github.com/richardwilkes/unison@v0.55.0/table.go:1029
                                      [github.com/richardwilkes/unison.(*Table[...]).DefaultDraw] C:/Users/Admin/go/pkg/mod/github.com/richardwilkes/unison@v0.55.0/table.go:240
                                      [github.com/richardwilkes/unison.(*Panel).Draw] C:/Users/Admin/go/pkg/mod/github.com/richardwilkes/unison@v0.55.0/panel.go:428
                                      [github.com/richardwilkes/unison.(*Panel).Draw] C:/Users/Admin/go/pkg/mod/github.com/richardwilkes/unison@v0.55.0/panel.go:446
                                      [github.com/richardwilkes/unison.(*Panel).Draw] C:/Users/Admin/go/pkg/mod/github.com/richardwilkes/unison@v0.55.0/panel.go:446
                                      [github.com/richardwilkes/unison.(*Panel).Draw] C:/Users/Admin/go/pkg/mod/github.com/richardwilkes/unison@v0.55.0/panel.go:446
                                      [github.com/richardwilkes/unison.(*Panel).Draw] C:/Users/Admin/go/pkg/mod/github.com/richardwilkes/unison@v0.55.0/panel.go:446
                                      [github.com/richardwilkes/unison.(*Window).Draw.func1] C:/Users/Admin/go/pkg/mod/github.com/richardwilkes/unison@v0.55.0/window.go:857
                                      [github.com/richardwilkes/toolbox.CallWithHandler] C:/Users/Admin/go/pkg/mod/github.com/richardwilkes/toolbox@v1.85.1/call.go:25
                                      [github.com/richardwilkes/toolbox.Call] C:/Users/Admin/go/pkg/mod/github.com/richardwilkes/toolbox@v1.85.1/call.go:19
                                      [github.com/richardwilkes/unison.(*Window).Draw] C:/Users/Admin/go/pkg/mod/github.com/richardwilkes/unison@v0.55.0/window.go:854
                                      [github.com/richardwilkes/unison.(*Window).draw] C:/Users/Admin/go/pkg/mod/github.com/richardwilkes/unison@v0.55.0/window.go:888
                                      [github.com/richardwilkes/unison.processEvents] C:/Users/Admin/go/pkg/mod/github.com/richardwilkes/unison@v0.55.0/app.go:172
                                      [github.com/richardwilkes/unison.Start] C:/Users/Admin/go/pkg/mod/github.com/richardwilkes/unison@v0.55.0/app.go:160
```

```
func (t *Table[T]) IsRowOrAnyParentSelected(index int) bool {
	if index < 0 || index >= len(t.rowCache) {
		return false
	}
	for index >= 0 {
		if t.selMap[t.rowCache[index].row.UUID()] {
			return true
		}
		index = t.rowCache[index].parent
	}
	return false
}
```

**Comment by ddkwork** [comment]
i  think is map reason, let me try another map replace it:

```
import (
	"testing"

	"github.com/ddkwork/golibrary/mylog"
	"github.com/google/uuid"
	cmap "github.com/orcaman/concurrent-map/v2"
)

func TestName(t *testing.T) {
	c := cmap.New[bool]()
	id := uuid.NewString()
	c.Set(id, true)
	mylog.Info("Count", c.Count())
	mylog.Struct(c.Keys())
	mylog.Struct(c.Items())
	mylog.Info("IsEmpty", c.IsEmpty())
	selected, b := c.Get(id)
	if !b {
		return
	}
	mylog.Info("Get", selected)
	c.Remove(id)
	mylog.Info("Count", c.Count())
	mylog.Info("IsEmpty", c.IsEmpty())
}
```

**Comment by ddkwork** [comment]
hi， i used another map replace it and run demo, the problem is still here. So how can i pad some many for you, please help me dynamic add node for table not all node set into once way, like   
Windows task manager, another problem is set paner size later, the scroll   
Is lost. Can you have Tencent weixin pay?

**Comment by richardwilkes** [comment]
It is a requirement that you always call `SetRootRows()` whenever the underlying data structure parent-child relationships change. This gives the table an opportunity to re-sync itself with your changes. When you make a change without doing so, you will cause panics, which is what you're experiencing here.

What I generally do when I need to alter the data structure parent-child relationship is get the current selection, make the data change, set the new root rows, then restore the selection. You can see that in my gcs project, which I know you've been looking at as well.

**Comment by ddkwork** [comment]
> It is a requirement that you always call `SetRootRows()` whenever the underlying data structure parent-child relationships change. This gives the table an opportunity to re-sync itself with your changes. When you make a change without doing so, you will cause panics, which is what you're experiencing here.
> 
> What I generally do when I need to alter the data structure parent-child relationship is get the current selection, make the data change, set the new root rows, then restore the selection. You can see that in my gcs project, which I know you've been looking at as well.

Hello, teacher, I don't know if I understand your answer accurately. What you said seems to be the creatitem method called by all docktable in gcs and the insertitem method of the operation node. According to your description, do you mean to update the current node? For example, the current table has four rows, so we need to insert a node in the node in the third row to make it into five rows. After the behavior of inserting a node occurs, the node list under root changes. At this time, all the children and children of root are calculated to get a node slice, and this result is set to the table as rowdate. Oh, I seem to understand what you mean. You seem to tell me that when adding, deleting and checking all the nodes of root, you need to recalculate the rows node slice and then fill it in the table. I seem to forget to calculate this and just fill in the children of root. The parent-child structure has changed, but the rows node slice has not been updated. Thank you for making such a great lib. You are the only tree table realized by the whole go language. Thank you for your contribution. Another problem is the collocation between the table and the scroll bar. Don't set the table size. The layout can't be controlled. After setting the size, the horizontal and vertical coordinates of the scroll bar are all 0 and disappear. I read a lot of code about the scroll bar in gcs, and some of them did operate pos. Then I tried to set the table size in demo, take out the scroll bar coordinates, reset X and Y to 0,78 and so on, and still couldn't see the scroll bar. The difficulty of this library is the table and layout, but I will keep studying hard. It's really great.

**Comment by ddkwork** [comment]
> It is a requirement that you always call `SetRootRows()` whenever the underlying data structure parent-child relationships change. This gives the table an opportunity to re-sync itself with your changes. When you make a change without doing so, you will cause panics, which is what you're experiencing here.
> 
> What I generally do when I need to alter the data structure parent-child relationship is get the current selection, make the data change, set the new root rows, then restore the selection. You can see that in my gcs project, which I know you've been looking at as well.

Sorry this still panicked by selmap

'''
func (d *demoRow) InsertItem(row *demoRow) {
d.AddChild(row)
selMap := make(map[uuid.UUID]bool)
selMap[row.id] = true
for _, child := range row.children {
selMap[child.id] = true
}
table.SetSelectionMap(selMap)
d.table.SizeColumnsToFit(true)
table.ScrollRowCellIntoView(table.LastSelectedRowIndex(), 0)
table.ScrollRowCellIntoView(table.FirstSelectedRowIndex(), 0)
d.table.SetRootRows(d.children)
d.table.EventuallySyncToModel()
}

func (d *demoRow) AddChild(c *demoRow) {
c.parent = d
d.children = append(d.children, c)
}
'''

**Comment by richardwilkes** [comment]
Whenever you get a panic, posting the stack trace text is important. Failure to do so means I have no way of knowing what the problem is.

Looking at what you posted above, the first thing I'd do is move the call to SetRootRows() up to after you collect the selMap, but before you call SetSelectionMap(). In addition, calling SetRootRoows() with d.children makes no sense whatsoever. You probably want to just do something like SetRootRows(RootRows()), since you've altered it in place and just want to trigger the logic that rebuilds things with the new data.

**Comment by ddkwork** [comment]
> Whenever you get a panic, posting the stack trace text is important. Failure to do so means I have no way of knowing what the problem is.
> 
> Looking at what you posted above, the first thing I'd do is move the call to SetRootRows() up to after you collect the selMap, but before you call SetSelectionMap(). In addition, calling SetRootRoows() with d.children makes no sense whatsoever. You probably want to just do something like SetRootRows(RootRows()), since you've altered it in place and just want to trigger the logic that rebuilds things with the new data.

hi
```
var root = newDemoRow()

func (d *demoRow) InsertItem(row *demoRow) {
	d.AddChild(row)
	d.table.SetRootRows(root.children)
	
	selMap := make(map[uuid.UUID]bool)
	selMap[row.id] = true
	for _, child := range row.children {
		selMap[child.id] = true
	}

	table.SetSelectionMap(selMap)
	d.table.EventuallySizeColumnsToFit(true)
	d.table.ScrollRowIntoView(d.table.LastRowIndex())
}

func (d *demoRow) AddChild(c *demoRow) {
	c.parent = d
	d.children = append(d.children, c)
}

ERR | 2023-06-12 | 07:59:16.264 | recovered from panic
                                      [example/demo.(*demoRow).UUID] C:/Users/Admin/Desktop/example/demo/demo_row.go:87
                                      [github.com/richardwilkes/unison.(*Table[...]).IsRowSelected] C:/Users/Admin/go/pkg/mod/github.com/richardwilkes/unison@v0.56.0/table.go:1042
                                      [github.com/richardwilkes/unison.(*Table[...]).cellParams] C:/Users/Admin/go/pkg/mod/github.com/richardwilkes/unison@v0.56.0/table.go:328
                                      [github.com/richardwilkes/unison.(*Table[...]).DefaultDraw] C:/Users/Admin/go/pkg/mod/github.com/richardwilkes/unison@v0.56.0/table.go:276
                                      [github.com/richardwilkes/unison.(*Panel).Draw] C:/Users/Admin/go/pkg/mod/github.com/richardwilkes/unison@v0.56.0/panel.go:428
                                      [github.com/richardwilkes/unison.(*Panel).Draw] C:/Users/Admin/go/pkg/mod/github.com/richardwilkes/unison@v0.56.0/panel.go:446
                                      [github.com/richardwilkes/unison.(*Panel).Draw] C:/Users/Admin/go/pkg/mod/github.com/richardwilkes/unison@v0.56.0/panel.go:446
                                      [github.com/richardwilkes/unison.(*Panel).Draw] C:/Users/Admin/go/pkg/mod/github.com/richardwilkes/unison@v0.56.0/panel.go:446
                                      [github.com/richardwilkes/unison.(*Panel).Draw] C:/Users/Admin/go/pkg/mod/github.com/richardwilkes/unison@v0.56.0/panel.go:446
                                      [github.com/richardwilkes/unison.(*Window).Draw.func1] C:/Users/Admin/go/pkg/mod/github.com/richardwilkes/unison@v0.56.0/window.go:857
                                      [github.com/richardwilkes/toolbox.CallWithHandler] C:/Users/Admin/go/pkg/mod/github.com/richardwilkes/toolbox@v1.85.1/call.go:25
                                      [github.com/richardwilkes/toolbox.Call] C:/Users/Admin/go/pkg/mod/github.com/richardwilkes/toolbox@v1.85.1/call.go:19
                                      [github.com/richardwilkes/unison.(*Window).Draw] C:/Users/Admin/go/pkg/mod/github.com/richardwilkes/unison@v0.56.0/window.go:854
                                      [github.com/richardwilkes/unison.(*Window).draw] C:/Users/Admin/go/pkg/mod/github.com/richardwilkes/unison@v0.56.0/window.go:888
                                      [github.com/richardwilkes/unison.NewWindow.func3] C:/Users/Admin/go/pkg/mod/github.com/richardwilkes/unison@v0.56.0/window.go:220
                                      [github.com/go-gl/glfw/v3.3/glfw.goWindowRefreshCB] C:/Users/Admin/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20221017161538-93cebf72946b/window.go:237
                                      [_cgoexp_b7f3ee334319_goWindowRefreshCB] _cgo_gotypes.go:2709
                                      [github.com/go-gl/glfw/v3.3/glfw._Cfunc_glfwWaitEvents] _cgo_gotypes.go:2489
                                      [github.com/go-gl/glfw/v3.3/glfw.WaitEvents] C:/Users/Admin/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20221017161538-93cebf72946b/window.go:982
                                      [github.com/richardwilkes/unison.processEvents] C:/Users/Admin/go/pkg/mod/github.com/richardwilkes/unison@v0.56.0/app.go:165
                                      [github.com/richardwilkes/unison.Start] C:/Users/Admin/go/pkg/mod/github.com/richardwilkes/unison@v0.56.0/app.go:160
                                      [main.main] C:/Users/Admin/Desktop/example/main.go:20
                                    Caused by: runtime error: invalid memory address or nil pointer dereference
ERR | 2023-06-12 | 07:59:16.353 | recovered from panic

```

**Comment by richardwilkes** [comment]
OK, so there are only two possibilities given where it panicked (well, two in my code -- I can't see your example code to see what it might be doing).

One, the selection map is nil. That's not possible unless you've modified the code, since it is initialized when the table is created and always only ever replaced with another valid map, so we can rule that out.

Two, you've added a nil row to either the root rows or one of the children in the tree. That's never permissible and I'm not going to add nil checks everywhere to guard against it.

In the code you've copied and pasted, I still see you doing this: `d.table.SetRootRows(root.children)`, which as I've stated before, is likely wrong. Are you sure `root.children` isn't nil?

Anyway, I'm sorry, but I'm not going to debug this for you any longer. It isn't practical for me and I don't have the time nor energy for it. I use this table extensively in other projects (both public and private) and do not have this issue.
