### ISSUE TITLE
Replace use of slice.ZeroedDelete with slices.Delete

### ISSUE THREAD

**Issue by mewmew** [richardwilkes/unison#42]
From the recently accepted proposal https://github.com/golang/go/issues/63393, slices.Delete will clear the tail, and thus slice.ZeroedDelete will no longer be needed.

**Comment by richardwilkes** [comment]
Once this makes it into the Go release, I'll update things accordingly. I couldn't tell at a glance if this was going to make it into the upcoming Go 1.22 release or not. Do you happen to know?

**Comment by mewmew** [comment]
It was implemented with commit https://github.com/golang/go/commit/e21dc702d54e85381a97259db7deec710108279b. If this one makes it to the 1.22 release or not, time will tell : )
