### ISSUE TITLE
Create a full-featured text editing widget that supports inline styling

### ISSUE THREAD

**Issue by ddkwork** [richardwilkes/unison#52]
Hi, can field add a color setting or callback function for text? Currently the foreground color of each text in lines is written to death, so if you want to implement syntax highlighting in the code editor, you can only change the source code. Also, strings' split function by line does not perform well for very long code. Currently the color doesn't feel right after I set the syntax coloring, to be investigated.
![Screenshot_20240425_175511_com.realvnc.viewer.android.jpg](https://github.com/richardwilkes/unison/assets/19886504/8832241c-8287-4806-9d44-b1153a41eab2)

**Comment by ddkwork** [comment]
Another weird issue is that the scrollbar needs to manually narrow the window a little bit each time for it to appear, which is weird.

**Comment by ddkwork** [comment]
Currently the split algorithm of text is not according to the syntax tree of each language or regular expression to divide the token, in order to get the correct color of the token, I can only call the third-party library to split the token, so that although I get the correct token and its color, but this may lead to the text of the other fields of the information to fill in the wrong incorrect, such as the width of what. I think this may be the reason for the coloring irregularities that are currently occurring.

**Comment by richardwilkes** [comment]
I'm not understanding what you're asking for. Please be specific.

**Comment by ddkwork** [comment]
I apologize for my poor English. What I meant is that field widgets need to add a callback function within the default draw method to support coloring features similar to rich text editors, currently the colors are fixed and can only be changed destructively. The short answer is that the lines field of the field widget, generally speaking, a text will have more than one token to form a line, currently the foreground color of the whole line is fixed, currently I use the field widget to implement the code editor widget, I need to set the foreground color of all the tokens of each text to complete the syntax coloring feature. After further investigation, simply adding a callback function may not be enough, but also need to export individual fields of the text to fill the color slice.



---Original---
From: "Richard ***@***.***&gt;
Date: Fri, Apr 26, 2024 04:28 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [richardwilkes/unison] Field set color (Issue #52)




 
I'm not understanding what you're asking for. Please be specific.

**Comment by richardwilkes** [comment]
I see. The Field widget was never intended to be a full-featured text editor, which is why it is designed to only support a single format throughout its content.

You're asking for a completely new widget suitable for something more complex than a simple text field. At some point, I'll probably build such a thing -- but I currently have no need for such a thing, so it isn't high on my list of things to work on.

**Comment by ddkwork** [comment]
Thanks, anyway, your overall design of this library is great.



---Original---
From: "Richard ***@***.***&gt;
Date: Fri, Apr 26, 2024 06:57 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [richardwilkes/unison] Field set color (Issue #52)




 
I see. The Field widget was never intended to be a full-featured text editor, which is why it is designed to only support a single format throughout its content.
 
You're asking for a completely new widget suitable for something more complex than a simple text field. At some point, I'll probably build such a thing -- but I currently have no need for such a thing, so it isn't high on my list of things to work on.

**Comment by ddkwork** [comment]
If we just display the coloring syntax, the rich text editor has rendered all the tokens properly, thanks to your invention of this library, which will make a set of ui libraries with almost the same full functionality as qt. Tomorrow I'll work on the coloring and performance testing of the field widgets

![Screenshot_20240427_011123_com.realvnc.viewer.android.jpg](https://github.com/richardwilkes/unison/assets/19886504/8c89be9b-ee76-4baf-bc25-40943ff37fdb)

**Comment by ddkwork** [comment]
![Screenshot_20240427_152130_com.realvnc.viewer.android.jpg](https://github.com/richardwilkes/unison/assets/19886504/2e72096c-c984-4076-b236-aa02866cb394)

finished，thx.
