### ISSUE TITLE
Unable to set a Label's text color

### ISSUE THREAD

**Issue by pekim** [richardwilkes/unison#60]
```go
	lbl := unison.NewLabel()
	lbl.SetTitle("Here be a label")
	// lbl.Text = "Here be a label"
	lbl.OnBackgroundInk = unison.Red
```

With 0.68.1 a label's text color can be set. But with 0.69.0 or later the label's `OnBackgroundInk` is not honoured. Is this deliberate? If it is, how can the label's color be set? Or have I simply overlooked or misunderstood something?

**Comment by richardwilkes** [comment]
This is an unfortunate side-effect of the change that allows rich text inside labels, which can allow for multi-colored text, among other things. The `OnBackgroundInk` color is only used when its TextDecoration is used to create new text, i.e. on calls to `.SetTitle()`.

The workaround is to do something like `label.SetTitle(label.String())` after changing the `OnBackgroundInk` or `Font`. Not great, I know. Unfortunately, I've yet to come up with a solution that allows for decorated text and easy changes like it used to have. If you have some ideas in this area, I'm open to suggestions.

**Comment by pekim** [comment]
I see, that explains it . So changing `OnBackgroundInk` before setting the title works just fine.

If `OnBackgroundInk` were not exported and a `SetOnBackgroundInk` method was required to be called. Then the new text could be created in the method (and similar methods). But as the api stands I don't see a way to improve the current situation.

Perhaps this can be mitigated to some degree with documentation. Although I don't know where the best place to mention it would be.

**Comment by richardwilkes** [comment]
Yes, but even that doesn't really work, since it would wipe out any formatting that might otherwise have been applied by someone that directly set the .Text field.

Perhaps I should not have merged Label and RichLabel together.

**Comment by richardwilkes** [comment]
... although I did that because in my projects that used unison, I kept finding places where a Label had been used for something that I wanted to be a RichLabel for something specific, but didn't want to require the use of RichLabel everywhere. Table cells, for example.

**Comment by ddkwork** [comment]
Instead, I host the current Merge Widgets mode, for which all you need to do is instantiate a text and set the foreground color!



---Original---
From: "Mike D ***@***.***&gt;
Date: Wed, Jul 3, 2024 03:24 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [richardwilkes/unison] Unable to set a Label's text color (Issue#60)




 
I see, that explains it . So changing OnBackgroundInk before setting the title works just fine.
 
If OnBackgroundInk were not exported and a SetOnBackgroundInk method was required to be called. Then the new text could be created in the method (and similar methods). But as the api stands I don't see a way to improve the current situation.
 
Perhaps this can be mitigated to some degree with documentation. Although I don't know where the best place to mention it would be.

**Comment by ddkwork** [comment]
Also, the table cell is not unsuitable for coloring scenarios, I will try to color it for displaying the debugger's disassembly code

**Comment by richardwilkes** [comment]
Closing as this is working as intended, if a bit awkwardly for some types of usage.
